name: thobio_joseph_personal_website
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  get: 4.6.5
  google_fonts: ^4.0.3
  timelines: ^0.1.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
